vim.cmd("set number relativenumber")
vim.cmd("set expandtab")
vim.cmd("set tabstop=2")
vim.cmd("set softtabstop=2")
vim.cmd("set shiftwidth=2")
--vim.cmd("inoremap ( ()<Esc>i")
--vim.cmd("inoremap { {}<Esc>i")
--vim.cmd("inoremap {<CR> {<CR>}<Esc>O")
--vim.cmd("inoremap [ []<Esc>i")
vim.cmd("inoremap < <><Esc>i")
--vim.cmd("inoremap ' ''<Esc>i")
--vim.cmd('inoremap " ""<Esc>i')
vim.keymap.set("n", "<leader>sr", ":vsplit<CR>")
vim.keymap.set("n", "<leader>srn", ":vnew<CR>")
vim.keymap.set("n", "<leader>wh", "<c-w>h<CR>")
vim.keymap.set("n", "<leader>wl", "<c-w>l<CR>")
vim.keymap.set("n", "<leader>cl", ":close<CR>")
vim.g.mapleader = " "
