vim.cmd("set number relativenumber")
vim.cmd("set wrap")
vim.cmd("set linebreak")
vim.cmd("set textwidth=80")
vim.cmd("set colorcolumn=80")
vim.cmd("set expandtab")
vim.cmd("set tabstop=2")
vim.cmd("set softtabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set clipboard=unnamedplus")

--vim.cmd("inoremap ( ()<Esc>i")
--vim.cmd("inoremap { {}<Esc>i")
--vim.cmd("inoremap {<CR> {<CR>}<Esc>O")
--vim.cmd("inoremap [ []<Esc>i", "")
vim.cmd("inoremap < <><Esc>i")
--vim.cmd("inoremap ' ''<Esc>i")
--vim.cmd('inoremap " ""<Esc>i')
--vim.keymap.set("n", "<leader>tr", ":vsplit<CR>")
--vim.keymap.set("n", "<leader>trn", ":vnew<CR>")
vim.keymap.set("n", "<leader>wl", "<c-w>h<CR>")
vim.keymap.set("n", "<leader>wr", "<c-w>l<CR>")
--vim.keymap.set("n", "<leader>cl", ":close<CR>")
vim.g.mapleader = " "
